---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Here are some plots

Today we are making interactive plots in plotly.

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

Do some initial data cleaning / subsetting.

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb |> 
  mutate(rating = review_scores_location / 2) |>
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) |>
  drop_na(rating) |>
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)
```

Use plotly to make some quick plots

```{r}
nyc_airbnb |>
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) |>
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    text = ~text_label, color = ~price, alpha = 0.5)
```

Box plot

```{r}
nyc_airbnb |> 
  plot_ly(y = ~price, x = ~neighbourhood, type = "box", colors = "viridis")

nyc_airbnb |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  plot_ly(y = ~price, color = ~neighbourhood, type = "box", colors = "viridis")
```

bar chart with number of rentals
```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, type = "bar", colors = "viridis")
```

